lesson_20/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from blogapp.api_views import SkillsViewSet, VacancyViewSet

router = routers.DefaultRouter()
router.register(r'skills', SkillsViewSet)
router.register(r'vacancyes', VacancyViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v0/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

lesson_20/blog/blogapp/urls.py
from django.urls import path
from blogapp import views

app_name = 'blogapp'

urlpatterns = [
    path('', views.VacancyListView.as_view(), name='index'),
    path('create/', views.VacancyCreateView.as_view(), name='create'),
    path('contact/', views.ContactCreateView().contact_view, name='contact'),
    path('skill-list', views.SkillsListView.as_view(), name='skills_list'),
    path('skill-detail/<int:pk>/', views.SkillsDetailView.as_view(), name='skill_detail'),
    path('post/<int:id>/', views.VacancyDetailView.as_view(), name='post'),
    path('skill-create/', views.SkillsCreateView.as_view(), name='skill_create'),
    path('skill-update/<int:pk>/', views.SkillsUpdataView.as_view(), name='skill_update'),
    path('skill-delete/<int:pk>/', views.SkillsDeleteView.as_view(), name='skill_delete'),
]

lesson_20/blog/blogapp/models.py
from django.db import models
from usersapp.models import BlogUser

# Create your models here.
class Skills(models.Model):
    name = models.CharField(max_length=32, unique=True)
    description = models.TextField(blank=True)
    def __str__(self):
        return self.name

class Vacancy(models.Model):
    name = models.CharField(max_length=32)
    areal = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    skills = models.ManyToManyField(Skills)
    image = models.ImageField(upload_to='posts', null=True, blank=True)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

    def has_image(self):
        return bool(self.image)

lesson_20/blog/blogapp/forms.py
from django import forms
from blogapp.models import Vacancy
from blogapp.models import Skills



class ContactForm(forms.Form):
    name = forms.CharField(label='Название')
    email = forms.EmailField(label='email')
    message = forms.CharField(label='Сообщение')


class PostForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        exclude = ['user']

    name = forms.CharField(label='Название',
                           widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))

    # Чекбоксы
    skills = forms.ModelMultipleChoiceField(queryset=Skills.objects.all(),
                                          widget=forms.CheckboxSelectMultiple())

    # class Meta:
    #     model = Vacancy
    #     fields = ('name',)

lesson_20/blog/blogapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .forms import ContactForm, PostForm
from django.core.mail import send_mail
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Vacancy
from .models import Skills
from django.views.generic.base import ContextMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class VacancyListView(ListView):
    model = Vacancy
    template_name = 'blogapp/index.html'
    context_object_name = 'vacancies'
    paginate_by = 2
    # title = 'Потрошение сайта hh.ru'

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        context['header'] = "страница вакансий"
        context['message'] = "Welcome to Python"
        return context

    def get_queryset(self):
        """
        Получение данных
        :return:
        """
        return Vacancy.objects.select_related('user').all()


class NameContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        context['name'] = 'СКИЛЛ'
        return context

class PostFormMixin(ContextMixin):
    def post(self, request, *args, **kwargs):
        """
        Пришел пост запрос
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        return super().post(request, *args, **kwargs)

class SkillsListView(ListView, NameContextMixin):
    model = Skills
    template_name = 'blogapp/skills_list.html'
    context_object_name = 'skills'
    paginate_by = 3

    def get_queryset(self):
        """
        Получение данных
        :return:
        """
        return Skills.objects.all()

class SkillsDetailView(DetailView, NameContextMixin):
    model = Skills
    template_name = 'blogapp/skill_detail.html'

    def get(self, request, *args, **kwargs):
        """
        Метод обработки get запроса
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        self.skill_id = kwargs['pk']
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """
        Получение этого объекта
        :param queryset:
        :return:
        """
        return get_object_or_404(Skills, pk=self.skill_id)

class SkillsCreateView(CreateView, NameContextMixin, PostFormMixin):
    # form_class =
    fields = '__all__'
    model = Skills
    success_url = reverse_lazy('blog:skills_list')
    template_name = 'blogapp/skill_create.html'

    def form_valid(self, form):
        """
        Метод срабатывает после того как форма валидна
        :param form:
        :return:
        """
        return super().form_valid(form)


class SkillsUpdataView(UpdateView):
    fields = '__all__'
    model = Skills
    success_url = reverse_lazy('blog:skills_list')
    template_name = 'blogapp/skill_create.html'

class SkillsDeleteView(DeleteView):
    template_name = 'blogapp/skill_delete.html'
    model = Skills
    success_url = reverse_lazy('blog:skills_list')


class ContactCreateView:

    def contact_view(self, request):
        if request.method == 'POST':
            form = ContactForm(request.POST)
            if form.is_valid():
                # Получить данные из форы
                name = form.cleaned_data['name']
                message = form.cleaned_data['message']
                email = form.cleaned_data['email']

                send_mail(
                    'Contact message',
                    f'Ваш сообщение {message} принято',
                    'volohov@aaanet.ru',
                    ['volohov@aaanet.ru'],
                    fail_silently=True,
                )

                return HttpResponseRedirect(reverse('blog:index'))
        else:
            form = ContactForm()
            return render(request, 'blogapp/contact.html', context={'form': form})


class VacancyCreateView(LoginRequiredMixin, CreateView, NameContextMixin, PostFormMixin):
    # form_class = PostForm
    fields = '__all__'
    model = Vacancy
    success_url = reverse_lazy('blog:index')
    template_name = 'blogapp/create.html'

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        context = super().get_context_data(*args, **kwargs)
        context['form'] = PostForm()
        return context
    def form_valid(self, form):
        """
        Метод срабатывает после того как форма валидна
        :param form:
        :return:
        """
        form.instance.user = self.request.user
        return super().form_valid(form)



class VacancyDetailView(DetailView, NameContextMixin):
    model = Vacancy
    template_name = 'blogapp/post.html'

    def get(self, request, *args, **kwargs):
        """
        Метод обработки get запроса
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        self.vacancy_id = kwargs['id']
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        """
        Получение этого объекта
        :param queryset:
        :return:
        """
        return get_object_or_404(Vacancy, id=self.vacancy_id)

lesson_20/blog/blogapp/templates/blogapp/contact.html
{% extends "base.html" %}

{% block title %}
    Не главная страница
{% endblock %}

{% block content %}
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form id="contactForm" method="post">
                                {%  csrf_token %}
                                {{ form.as_p}}

                                <!-- Submit Button-->
                                <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

lesson_20/blog/blogapp/templates/blogapp/create.html
{% extends "base.html" %}

{% block title %}
Создание поста
{% endblock %}



{% block content %}
<div class="row">
    <h1>СОЗДАНИЕ НОВОЙ ВАКАНСИИ </h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

lesson_20/blog/blogapp/templates/blogapp/index.html
{% extends "base.html" %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    Количество вакансий на странице: {{vacancies|length}}
                    <!-- Post preview-->
                   <h1>{{ header }} {{ page_obj.number }}</h1>

                        {% for item in vacancies %}
                            <div class="post-preview">
                                <a href="{% url 'blog:post'  id=item.id %}">
                                    <h2 class="post-title">Вакансия {{item.name}}, регион {{item.areal}}</h2>
                                    <h3 class="post-subtitle">Автор поста {{item.user.username}}</h3>
                                    <h3 class="post-subtitle">{{item.description}}</h3>
                                </a>
                                <p class="post-meta">
                                    Posted by
                                    <a href="#!">Start Bootstrap</a>
                                    on September 24, 2023
                                    {% if item.has_image %}
                                        Есть картинка
                                        {% else%}
                                        Нет картинки
                                    {% endif %}
                                        {{item.has_image}}
                                        {{item.some_method}}
                                </p>
                            </div>

                        {% endfor %}

                    <!-- Pager-->
                </div>
            <div class="clearfix">
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; первая |</a>
                            <a href="?page={{ page_obj.previous_page_number }}">предыдущая |</a>
                        {% endif %}

                        <span class="current">
                            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">| следующая</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">| последняя &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>

        </div>


{% endblock %}

lesson_20/blog/blogapp/templates/blogapp/post.html
{% extends "base.html" %}

{% block title %}
    {{post.name}}
{% endblock %}

{% block content %}
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                <p>Это вакансия {{vacancy.name}}</p>
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        {% if vacancy.image %}
                            <p><img src="{{vacancy.image.url}}" width="100"> {{vacancy.description}}</p>
                        {% else %}
                            <p></p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </article>
{% endblock %}

lesson_20/blog/blogapp/templates/blogapp/skill_create.html
{% extends "base.html" %}

{% block title %}
Создание скилла
{% endblock %}

{% block content %}
<div class="row">
    <h1>СОЗДАНИЕ НОВОГО {{name}}А</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

lesson_20/blog/blogapp/templates/blogapp/skill_delete.html
{% extends "base.html" %}

{% block title %}
{{object.name}}
{% endblock%}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.name}}
    </div>

    Вы уверены?
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
    </form>
</div>
{% endblock %}

lesson_20/blog/blogapp/templates/blogapp/skill_detail.html
{% extends "base.html" %}

{% block title %}
{{post.name}}
{% endblock%}

{% block content %}
<div class="row">
    <h1>{{name}}</h1>
    <div class="col-lg-8 col-md-10 mx-auto">
        {{object.name}}
        <a href="{% url 'blog:skill_update' pk=object.pk %}"><font size="2" face="Arial">/ Изменить<font size="2" face="Arial"></font></a>
    </div>
</div>
{% endblock %}

lesson_20/blog/blogapp/templates/blogapp/skills_list.html
{% extends "base.html" %}

{% block title %}
Список скиллов
{% endblock %}

{% block content %}
<h1>{{name}}Ы</h1>
<ul>
    {% for item in object_list %}
    <li>
        <a href="{% url 'blog:skill_detail' pk=item.pk %}">{{item.name}}</a>
        </a><font size="2" face="Arial">
        /
        <a href="{% url 'blog:skill_update' pk=item.pk %}">Изменить</a>
        /
        <a href="{% url 'blog:skill_delete' pk=item.pk %}">Удалить</a></font>
    </li>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; первая |</a>
                <a href="?page={{ page_obj.previous_page_number }}">предыдущая |</a>
            {% endif %}

            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">| следующая</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">| последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
    <a href="{% url 'blog:skill_create' %}"><font size="2" face="Arial">Создать</font></a>
</ul>
{% endblock %}