lesson_20/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from blogapp.api_views import SkillsViewSet, VacancyViewSet

router = routers.DefaultRouter()
router.register(r'skills', SkillsViewSet)
router.register(r'vacancyes', VacancyViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog')),
    path('users/', include('usersapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v0/', include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

lesson_20/blog/blogapp/urls.py
from django.urls import path
from blogapp import views

app_name = 'blogapp'

urlpatterns = [
    path('', views.VacancyListView.as_view(), name='index'),
    path('create/', views.VacancyCreateView.as_view(), name='create'),
    path('contact/', views.ContactCreateView().contact_view, name='contact'),
    path('skill-list', views.SkillsListView.as_view(), name='skills_list'),
    path('skill-detail/<int:pk>/', views.SkillsDetailView.as_view(), name='skill_detail'),
    path('post/<int:id>/', views.VacancyDetailView.as_view(), name='post'),
    path('skill-create/', views.SkillsCreateView.as_view(), name='skill_create'),
    path('skill-update/<int:pk>/', views.SkillsUpdataView.as_view(), name='skill_update'),
    path('skill-delete/<int:pk>/', views.SkillsDeleteView.as_view(), name='skill_delete'),
]

lesson_20/blog/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView

app_name = 'usersapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('updatetoken/', views.update_token, name='update_token'),
]

lesson_20/blog/templates/base.html
{% load static %}
{% load str_extensions %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>

<body>

<!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:index' %}">Главная</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:contact' %}">Написать письмо</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:create' %}">Создать пост</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:skills_list' %}">Список скиллов</a></li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">Привет, <a href="{% url 'users:profile' pk=user.pk %}">{{user.username}}</a>
                                <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:logout' %}">{{user.username}} / Выход</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:login' %}">Вход</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:register' %}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

<!-- Page Header -->
        <header class="masthead" style="background-image: url('assets/img/contact-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>
                          Потрошение сайта hh.ru {{header|capitalize}} {{ page_obj.number }}
                            </h1>
                            <span class="subheading">Самые свежие вакансии</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>

<!-- Main Content -->
<div class="container">
    {% block content %}{% endblock %}
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">{{joke}}</p>
            </div>
        </div>
    </div>
</footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>

</body>

</html>